Repository brevansio/PRChecker, pull requests merged in 2021-11, with the labels that each got.

#11 Show pull request list in menu bar
  PRChecker/PRChecker.xcodeproj/project.pbxproj
  PRChecker/Shared/Common Views/CheckBox.swift
  PRChecker/Shared/Models/PullRequest.swift
  PRChecker/Shared/PRCheckerApp.swift
  PRChecker/macOS/AppDelegate.swift
  PRChecker/macOS/Controllers/MenuController.swift
  PRChecker/macOS/Unique Views/MenuBarPRCell.swift
  PRChecker/macOS/Unique Views/MenuView.swift
Labels: enhancement

#15 Add hover effect to PR cells and fix to focus on the popover when it's clicked
  PRChecker/Shared/Unique Views/PullRequestCell.swift
  PRChecker/Shared/Unique Views/SettingsView.swift
  PRChecker/macOS/AppDelegate.swift
  PRChecker/macOS/Controllers/MenuController.swift
  PRChecker/macOS/Unique Views/MenuBarPRCell.swift
  PRChecker/macOS/Unique Views/MenuView.swift
Labels: bug, enhancement

#27 Fix Uniqueness of PR IDs
  PRChecker/Shared/GraphQL/NetworkService.swift
  PRChecker/Shared/Models/AbstractPullRequest.swift
  PRChecker/Shared/Models/OldPullRequest.swift
  PRChecker/Shared/Models/PullRequest.swift
  PRChecker/Shared/Unique Views/PRListView.swift
  PRChecker/Shared/Unique Views/PullRequestCell.swift
  PRChecker/macOS/Unique Views/MenuBarPRCell.swift
Labels: bug

#28 Expand the settings
  PRChecker/PRChecker.xcodeproj/project.pbxproj
  PRChecker/Shared/Constants.swift
  PRChecker/Shared/GraphQL/NetworkService.swift
  PRChecker/Shared/SavedData.swift
  PRChecker/Shared/Unique Views/ContentView.swift
  PRChecker/Shared/Unique Views/DisplayOptionView.swift
  PRChecker/Shared/Unique Views/LoginView.swift
  PRChecker/Shared/Unique Views/RefreshSettingsView.swift
  PRChecker/Shared/Unique Views/SettingsView.swift
  PRChecker/Shared/Unique Views/WatchedListView.swift
  PRChecker/Shared/ViewModels/LoginInfoViewModel.swift
  PRChecker/Shared/ViewModels/PRListViewModel.swift
  PRChecker/Shared/ViewModels/SettingsViewModel.swift
Labels: enhancement

#30 [UI] Make Drop UI more like normal macOS app
  PRChecker/Shared/PRCheckerApp.swift
  PRChecker/Shared/Unique Views/ContentView.swift
  PRChecker/Shared/Unique Views/FilterView.swift
  PRChecker/Shared/Unique Views/PRListView.swift
Labels: improvement
